### ISSUE TITLE
Error getting tf between world and camera

### ISSUE THREAD

**Issue by brunoeducsantos** [swyphcosmo/ros-camera-lidar-calibration#5]
Hi @swyphcosmo ,
Thanks for the great repository.
I am having the following issue:

```
[ERROR] [1561999450.853570, 0.000000]: bad callback: <bound method LidarRGB.imageCallback of <__main__.LidarRGB instance at 0x7fc7c9b053b0>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/bruno/catkin_ws/src/ros-camera-lidar-calibration/scripts/lidar_image_calibration/lidar_rgb.py", line 57, in imageCallback
    translation = translation + ( 1,  )
TypeError: can only concatenate list (not "tuple") to list

```
This issue occurs in **lidar_rgb.py** . I tried to use wait_transform but I could not any result from velodyne_rgb_points.

Any ideas?

Thanks,
Bruno

**Comment by swyphcosmo** [comment]
@BrunoEduardoCSantos Unfortunately, I don't use ROS in my day to day any more so I don't have much insight. 

This could be due to a ROS version mismatch. I originally wrote these scripts in ROS Indigo (see the vagrant file image name), but you're running in ROS Kinetic (from the first line in the Traceback). My guess is that the callback signature changed between the two versions.

**Comment by AhmedAbdlhamid** [comment]
replace it with translation = tuple(translation) + ( 1,  )
